version = 1
SPDX-PackageName = "license-change"
SPDX-PackageSupplier = "Igor Mironchik <igor.mironchik@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/igormironchik/license-change"

[[annotations]]
path = ["doc/licensechange.png", "src/app/*.ui", "src/app/app.ico", "src/app/app.rc", "src/app/resources.qrc", "README.md", "REUSE.toml", "**/CMakeLists.txt", ".gitignore"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Igor Mironchik <igor.mironchik@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["src/app/img/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2007 Nuno Pinheiro <nuno@oxygen-icons.org>, 2007 David Vignoni <david@icon-king.com>, 2007 David Miller <miller@oxygen-icons.org>, Johann Ollivier Lapeyre <johann@oxygen-icons.org>, Kenneth Wimer <kwwii@bootsplash.org>, 2007 Riccardo Iaconelli <riccardo@oxygen-icons.org>"
SPDX-License-Identifier = "LGPL-3.0-or-later"
